// <auto-generated />
using System;
using CVTech.GestionIdentite.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.GestionIdentite.Infrastructure.Migrations
{
    [DbContext(typeof(IdentiteDbContext))]
    partial class IdentiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CVTech.GestionIdentite.Domaine.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<bool>("EstBloque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MotDePasseHache");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeUtilisateur")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasDiscriminator<string>("TypeUtilisateur").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CVTech.GestionIdentite.Domaine.Administrateur", b =>
                {
                    b.HasBaseType("CVTech.GestionIdentite.Domaine.Utilisateur");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.ToTable("Utilisateurs", t =>
                        {
                            t.Property("Nom")
                                .HasColumnName("Administrateur_Nom");
                        });

                    b.HasDiscriminator().HasValue("Administrateur");
                });

            modelBuilder.Entity("CVTech.GestionIdentite.Domaine.ProfilCandidat", b =>
                {
                    b.HasBaseType("CVTech.GestionIdentite.Domaine.Utilisateur");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("CVTech.GestionIdentite.Domaine.ProfilEntreprise", b =>
                {
                    b.HasBaseType("CVTech.GestionIdentite.Domaine.Utilisateur");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Entreprise");
                });
#pragma warning restore 612, 618
        }
    }
}
