// <auto-generated />
using System;
using CVTech.AppelOffreFreelance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.AppelOffreFreelance.Infrastructure.Migrations
{
    [DbContext(typeof(AppelOffreFreelanceDbContext))]
    partial class AppelOffreFreelanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CVTech.AppelOffreFreelance.Domaine.AppelOffre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomaineMetierCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LaureatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppelsOffres", (string)null);
                });

            modelBuilder.Entity("CVTech.AppelOffreFreelance.Domaine.PropositionFreelance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppelOffreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeEstimeeJours")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxJournalier")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppelOffreId", "FreelanceId")
                        .IsUnique();

                    b.ToTable("Propositions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
