// <auto-generated />
using System;
using CVTech.CatalogueEmploi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.CatalogueEmploi.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogueEmploiDbContext))]
    [Migration("20260615150751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CVTech.CatalogueEmploi.Domaine.AnnonceEmploi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomaineMetierCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprimee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Annonces", (string)null);
                });

            modelBuilder.Entity("CVTech.CatalogueEmploi.Domaine.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnnonceEmploiId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnnonceEmploiId", "CandidatId")
                        .IsUnique();

                    b.ToTable("Candidatures", (string)null);
                });

            modelBuilder.Entity("CVTech.CatalogueEmploi.Domaine.CurriculumVitae", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Competences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateDerniereModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId")
                        .IsUnique();

                    b.ToTable("CurriculumsVitae", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
